//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investments.Advisor.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Investments.Advisor.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;symbol&quot;: &quot;FP&quot;,
        ///		&quot;name&quot;: &quot;FONDUL PROPRIETATEA&quot;,
        ///		&quot;price&quot;: 1.3450,
        ///		&quot;weight&quot;: 0.2305
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;TLV&quot;,
        ///		&quot;name&quot;: &quot;BANCA TRANSILVANIA S.A.&quot;,
        ///		&quot;price&quot;: 2.5050,
        ///		&quot;weight&quot;: 0.1968
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;SNP&quot;,
        ///		&quot;name&quot;: &quot;OMV PETROM S.A.&quot;,
        ///		&quot;price&quot;: 0.4040,
        ///		&quot;weight&quot;: 0.1698
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;BRD&quot;,
        ///		&quot;name&quot;: &quot;BRD - GROUPE SOCIETE GENERALE S.A.&quot;,
        ///		&quot;price&quot;: 15.4800,
        ///		&quot;weight&quot;: 0.1067
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;SNG&quot;,
        ///		&quot;name&quot;: &quot;S.N.G.N. ROMGAZ S.A.&quot;,
        ///		&quot;price&quot;: 34.8500,
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bvb_index {
            get {
                return ResourceManager.GetString("bvb_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;symbol&quot;: &quot;FP&quot;,
        ///		&quot;name&quot;: &quot;FONDUL PROPRIETATEA&quot;,
        ///		&quot;price&quot;: 1.3450,
        ///		&quot;weight&quot;: 0.2305
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;TLV&quot;,
        ///		&quot;name&quot;: &quot;BANCA TRANSILVANIA S.A.&quot;,
        ///		&quot;price&quot;: 2.5050,
        ///		&quot;weight&quot;: 0.1968
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;SNP&quot;,
        ///		&quot;name&quot;: &quot;OMV PETROM S.A.&quot;,
        ///		&quot;price&quot;: 0.4040,
        ///		&quot;weight&quot;: 0.1698
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;BRD&quot;,
        ///		&quot;name&quot;: &quot;BRD - GROUPE SOCIETE GENERALE S.A.&quot;,
        ///		&quot;price&quot;: 15.4800,
        ///		&quot;weight&quot;: 0.1067
        ///	},
        ///	{
        ///		&quot;symbol&quot;: &quot;SNG&quot;,
        ///		&quot;name&quot;: &quot;S.N.G.N. ROMGAZ S.A.&quot;,
        ///		&quot;price&quot;: 34.8500,
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bvb_index_pascal_case {
            get {
                return ResourceManager.GetString("bvb_index_pascal_case", resourceCulture);
            }
        }
    }
}
